// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(cass_ffiFFI)
import cass_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cass_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cass_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCassFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol CassEngineProtocol: AnyObject, Sendable {
    
    /**
     * Close the engine: drop the SearchClient (Tantivy reader + SQLite
     * fallback), then drop the storage worker handle so its thread sees
     * the channel close, runs `FrankenStorage::close` (SQLite checkpoint),
     * and exits. Idempotent; subsequent method calls return a clean
     * `engine-closed` error.
     */
    func close() throws 
    
    /**
     * Returns the on-disk path the engine was opened against. Useful
     * for diagnostics and for the curation flows that need the
     * bundle-scoped data dir without re-resolving it.
     */
    func dataDir()  -> String
    
    /**
     * Window of `before` messages preceding and `after` messages
     * following the message at `(conversation_id, message_idx)`.
     * Anchor not found falls back to the conversation start (returns
     * the first `before+after+1` messages). Built atop
     * `FrankenStorage::fetch_messages`; routes through the storage
     * worker actor.
     */
    func expandAround(conversationId: Int64, messageIdx: Int64, before: UInt32, after: UInt32) async throws  -> [Message]
    
    /**
     * List every workspace cass has indexed at least one conversation
     * under. Routes through the storage worker actor.
     */
    func listWorkspaces() async throws  -> [Workspace]
    
    /**
     * Load a full conversation by its on-disk source path (the same
     * `source_path` cass returns on each `SearchHit`). Returns `None`
     * when no conversation matches that path. Routes through the
     * storage worker actor.
     */
    func loadConversation(sourcePath: String) async throws  -> Conversation?
    
    /**
     * Lexical / hybrid / semantic search across the indexed corpus.
     * Currently only `Lexical` is wired; the other variants return
     * `not-yet-implemented` until their dispatch lands in subsequent
     * passes.
     */
    func search(query: String, opts: SearchOpts) async throws  -> [SearchHit]
    
    /**
     * Returns the cass-ffi crate version. Verified to round-trip through
     * the UniFFI scaffolding by `cargo run --bin uniffi-bindgen` +
     * downstream Swift consumers.
     */
    func version()  -> String
    
}
open class CassEngine: CassEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cass_ffi_fn_clone_cassengine(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cass_ffi_fn_free_cassengine(handle, $0) }
    }

    
    /**
     * Open a CassEngine against an existing cass data directory. The
     * directory must contain `agent_search.db` (cass's canonical SQLite
     * store) and the `index/<schema-version>/` Tantivy index that cass
     * emits during `cass index`. Both halves of the concurrency model
     * (search-side `Arc<SearchClient>` + storage-side worker thread)
     * come up here; failures during either rollback the other.
     */
public static func `open`(dataDir: String)throws  -> CassEngine  {
    return try  FfiConverterTypeCassEngine_lift(try rustCallWithError(FfiConverterTypeCassError_lift) {
    uniffi_cass_ffi_fn_constructor_cassengine_open(
        FfiConverterString.lower(dataDir),$0
    )
})
}
    
    /**
     * Smoke-test constructor. Returns a non-functional engine carrying
     * only the crate version string. Used by the xcframework build script
     * to verify the bridge symbols actually link without going through
     * the disk-touching `open` path.
     */
public static func probe() -> CassEngine  {
    return try!  FfiConverterTypeCassEngine_lift(try! rustCall() {
    uniffi_cass_ffi_fn_constructor_cassengine_probe($0
    )
})
}
    

    
    /**
     * Close the engine: drop the SearchClient (Tantivy reader + SQLite
     * fallback), then drop the storage worker handle so its thread sees
     * the channel close, runs `FrankenStorage::close` (SQLite checkpoint),
     * and exits. Idempotent; subsequent method calls return a clean
     * `engine-closed` error.
     */
open func close()throws   {try rustCallWithError(FfiConverterTypeCassError_lift) {
    uniffi_cass_ffi_fn_method_cassengine_close(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Returns the on-disk path the engine was opened against. Useful
     * for diagnostics and for the curation flows that need the
     * bundle-scoped data dir without re-resolving it.
     */
open func dataDir() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_cass_ffi_fn_method_cassengine_data_dir(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Window of `before` messages preceding and `after` messages
     * following the message at `(conversation_id, message_idx)`.
     * Anchor not found falls back to the conversation start (returns
     * the first `before+after+1` messages). Built atop
     * `FrankenStorage::fetch_messages`; routes through the storage
     * worker actor.
     */
open func expandAround(conversationId: Int64, messageIdx: Int64, before: UInt32, after: UInt32)async throws  -> [Message]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cass_ffi_fn_method_cassengine_expand_around(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(conversationId),FfiConverterInt64.lower(messageIdx),FfiConverterUInt32.lower(before),FfiConverterUInt32.lower(after)
                )
            },
            pollFunc: ffi_cass_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cass_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cass_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeMessage.lift,
            errorHandler: FfiConverterTypeCassError_lift
        )
}
    
    /**
     * List every workspace cass has indexed at least one conversation
     * under. Routes through the storage worker actor.
     */
open func listWorkspaces()async throws  -> [Workspace]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cass_ffi_fn_method_cassengine_list_workspaces(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_cass_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cass_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cass_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeWorkspace.lift,
            errorHandler: FfiConverterTypeCassError_lift
        )
}
    
    /**
     * Load a full conversation by its on-disk source path (the same
     * `source_path` cass returns on each `SearchHit`). Returns `None`
     * when no conversation matches that path. Routes through the
     * storage worker actor.
     */
open func loadConversation(sourcePath: String)async throws  -> Conversation?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cass_ffi_fn_method_cassengine_load_conversation(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(sourcePath)
                )
            },
            pollFunc: ffi_cass_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cass_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cass_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeConversation.lift,
            errorHandler: FfiConverterTypeCassError_lift
        )
}
    
    /**
     * Lexical / hybrid / semantic search across the indexed corpus.
     * Currently only `Lexical` is wired; the other variants return
     * `not-yet-implemented` until their dispatch lands in subsequent
     * passes.
     */
open func search(query: String, opts: SearchOpts)async throws  -> [SearchHit]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cass_ffi_fn_method_cassengine_search(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(query),FfiConverterTypeSearchOpts_lower(opts)
                )
            },
            pollFunc: ffi_cass_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cass_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cass_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeSearchHit.lift,
            errorHandler: FfiConverterTypeCassError_lift
        )
}
    
    /**
     * Returns the cass-ffi crate version. Verified to round-trip through
     * the UniFFI scaffolding by `cargo run --bin uniffi-bindgen` +
     * downstream Swift consumers.
     */
open func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_cass_ffi_fn_method_cassengine_version(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCassEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CassEngine

    public static func lift(_ handle: UInt64) throws -> CassEngine {
        return CassEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CassEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CassEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CassEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCassEngine_lift(_ handle: UInt64) throws -> CassEngine {
    return try FfiConverterTypeCassEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCassEngine_lower(_ value: CassEngine) -> UInt64 {
    return FfiConverterTypeCassEngine.lower(value)
}




/**
 * A conversation projected to FFI-safe types. `messages` is the full
 * message list as cass returns it; for paginated reads use
 * `expand_around` with a (conversation_id, message_idx) anchor.
 */
public struct Conversation: Equatable, Hashable {
    public var id: Int64?
    public var agentSlug: String
    public var workspacePath: String?
    public var externalId: String?
    public var title: String?
    public var sourcePath: String
    public var startedAtMs: Int64?
    public var endedAtMs: Int64?
    public var approxTokens: Int64?
    public var messages: [Message]
    public var sourceId: String
    public var originHost: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64?, agentSlug: String, workspacePath: String?, externalId: String?, title: String?, sourcePath: String, startedAtMs: Int64?, endedAtMs: Int64?, approxTokens: Int64?, messages: [Message], sourceId: String, originHost: String?) {
        self.id = id
        self.agentSlug = agentSlug
        self.workspacePath = workspacePath
        self.externalId = externalId
        self.title = title
        self.sourcePath = sourcePath
        self.startedAtMs = startedAtMs
        self.endedAtMs = endedAtMs
        self.approxTokens = approxTokens
        self.messages = messages
        self.sourceId = sourceId
        self.originHost = originHost
    }

    

    
}

#if compiler(>=6)
extension Conversation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConversation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Conversation {
        return
            try Conversation(
                id: FfiConverterOptionInt64.read(from: &buf), 
                agentSlug: FfiConverterString.read(from: &buf), 
                workspacePath: FfiConverterOptionString.read(from: &buf), 
                externalId: FfiConverterOptionString.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                sourcePath: FfiConverterString.read(from: &buf), 
                startedAtMs: FfiConverterOptionInt64.read(from: &buf), 
                endedAtMs: FfiConverterOptionInt64.read(from: &buf), 
                approxTokens: FfiConverterOptionInt64.read(from: &buf), 
                messages: FfiConverterSequenceTypeMessage.read(from: &buf), 
                sourceId: FfiConverterString.read(from: &buf), 
                originHost: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Conversation, into buf: inout [UInt8]) {
        FfiConverterOptionInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.agentSlug, into: &buf)
        FfiConverterOptionString.write(value.workspacePath, into: &buf)
        FfiConverterOptionString.write(value.externalId, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterString.write(value.sourcePath, into: &buf)
        FfiConverterOptionInt64.write(value.startedAtMs, into: &buf)
        FfiConverterOptionInt64.write(value.endedAtMs, into: &buf)
        FfiConverterOptionInt64.write(value.approxTokens, into: &buf)
        FfiConverterSequenceTypeMessage.write(value.messages, into: &buf)
        FfiConverterString.write(value.sourceId, into: &buf)
        FfiConverterOptionString.write(value.originHost, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversation_lift(_ buf: RustBuffer) throws -> Conversation {
    return try FfiConverterTypeConversation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversation_lower(_ value: Conversation) -> RustBuffer {
    return FfiConverterTypeConversation.lower(value)
}


/**
 * A single message inside a conversation. Mirrors cass-internal
 * `crate::model::types::Message` minus the runtime-only `extra_json` /
 * `snippets` fields, which UniFFI cannot represent without a richer
 * JSON value type. Those are owned by curation flows that live above
 * this surface.
 */
public struct Message: Equatable, Hashable {
    public var id: Int64?
    public var idx: Int64
    public var role: MessageRole
    public var author: String?
    public var createdAtMs: Int64?
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64?, idx: Int64, role: MessageRole, author: String?, createdAtMs: Int64?, content: String) {
        self.id = id
        self.idx = idx
        self.role = role
        self.author = author
        self.createdAtMs = createdAtMs
        self.content = content
    }

    

    
}

#if compiler(>=6)
extension Message: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Message {
        return
            try Message(
                id: FfiConverterOptionInt64.read(from: &buf), 
                idx: FfiConverterInt64.read(from: &buf), 
                role: FfiConverterTypeMessageRole.read(from: &buf), 
                author: FfiConverterOptionString.read(from: &buf), 
                createdAtMs: FfiConverterOptionInt64.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Message, into buf: inout [UInt8]) {
        FfiConverterOptionInt64.write(value.id, into: &buf)
        FfiConverterInt64.write(value.idx, into: &buf)
        FfiConverterTypeMessageRole.write(value.role, into: &buf)
        FfiConverterOptionString.write(value.author, into: &buf)
        FfiConverterOptionInt64.write(value.createdAtMs, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lift(_ buf: RustBuffer) throws -> Message {
    return try FfiConverterTypeMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lower(_ value: Message) -> RustBuffer {
    return FfiConverterTypeMessage.lower(value)
}


/**
 * A single search hit projected to FFI-safe types. The shape mirrors
 * cass-internal `SearchHit` (src/search/query.rs:1231) but flattens the
 * `MatchType` enum into a snake_case string and casts `usize` →
 * `Option<u64>` (`line_number`) so UniFFI can emit a stable Swift type
 * across 32/64-bit targets.
 */
public struct SearchHit: Equatable, Hashable {
    public var title: String
    public var snippet: String
    public var content: String
    public var score: Float
    public var sourcePath: String
    public var agent: String
    public var workspace: String
    public var workspaceOriginal: String?
    public var createdAtMs: Int64?
    public var lineNumber: UInt64?
    public var matchType: String
    public var sourceId: String
    public var originKind: String
    public var originHost: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, snippet: String, content: String, score: Float, sourcePath: String, agent: String, workspace: String, workspaceOriginal: String?, createdAtMs: Int64?, lineNumber: UInt64?, matchType: String, sourceId: String, originKind: String, originHost: String?) {
        self.title = title
        self.snippet = snippet
        self.content = content
        self.score = score
        self.sourcePath = sourcePath
        self.agent = agent
        self.workspace = workspace
        self.workspaceOriginal = workspaceOriginal
        self.createdAtMs = createdAtMs
        self.lineNumber = lineNumber
        self.matchType = matchType
        self.sourceId = sourceId
        self.originKind = originKind
        self.originHost = originHost
    }

    

    
}

#if compiler(>=6)
extension SearchHit: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                title: FfiConverterString.read(from: &buf), 
                snippet: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                score: FfiConverterFloat.read(from: &buf), 
                sourcePath: FfiConverterString.read(from: &buf), 
                agent: FfiConverterString.read(from: &buf), 
                workspace: FfiConverterString.read(from: &buf), 
                workspaceOriginal: FfiConverterOptionString.read(from: &buf), 
                createdAtMs: FfiConverterOptionInt64.read(from: &buf), 
                lineNumber: FfiConverterOptionUInt64.read(from: &buf), 
                matchType: FfiConverterString.read(from: &buf), 
                sourceId: FfiConverterString.read(from: &buf), 
                originKind: FfiConverterString.read(from: &buf), 
                originHost: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.snippet, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
        FfiConverterString.write(value.sourcePath, into: &buf)
        FfiConverterString.write(value.agent, into: &buf)
        FfiConverterString.write(value.workspace, into: &buf)
        FfiConverterOptionString.write(value.workspaceOriginal, into: &buf)
        FfiConverterOptionInt64.write(value.createdAtMs, into: &buf)
        FfiConverterOptionUInt64.write(value.lineNumber, into: &buf)
        FfiConverterString.write(value.matchType, into: &buf)
        FfiConverterString.write(value.sourceId, into: &buf)
        FfiConverterString.write(value.originKind, into: &buf)
        FfiConverterOptionString.write(value.originHost, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


/**
 * Time window filter shared by `SearchOpts` and `SessionFilter`.
 */
public struct TimeFilter: Equatable, Hashable {
    public var afterMs: Int64?
    public var beforeMs: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(afterMs: Int64?, beforeMs: Int64?) {
        self.afterMs = afterMs
        self.beforeMs = beforeMs
    }

    

    
}

#if compiler(>=6)
extension TimeFilter: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimeFilter: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimeFilter {
        return
            try TimeFilter(
                afterMs: FfiConverterOptionInt64.read(from: &buf), 
                beforeMs: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TimeFilter, into buf: inout [UInt8]) {
        FfiConverterOptionInt64.write(value.afterMs, into: &buf)
        FfiConverterOptionInt64.write(value.beforeMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeFilter_lift(_ buf: RustBuffer) throws -> TimeFilter {
    return try FfiConverterTypeTimeFilter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimeFilter_lower(_ value: TimeFilter) -> RustBuffer {
    return FfiConverterTypeTimeFilter.lower(value)
}


/**
 * A workspace cass has indexed at least one conversation under.
 */
public struct Workspace: Equatable, Hashable {
    public var id: Int64?
    public var path: String
    public var displayName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64?, path: String, displayName: String?) {
        self.id = id
        self.path = path
        self.displayName = displayName
    }

    

    
}

#if compiler(>=6)
extension Workspace: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspace: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Workspace {
        return
            try Workspace(
                id: FfiConverterOptionInt64.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Workspace, into buf: inout [UInt8]) {
        FfiConverterOptionInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterOptionString.write(value.displayName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspace_lift(_ buf: RustBuffer) throws -> Workspace {
    return try FfiConverterTypeWorkspace.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspace_lower(_ value: Workspace) -> RustBuffer {
    return FfiConverterTypeWorkspace.lower(value)
}


/**
 * Stable error envelope across the FFI boundary. `kind` is the branch
 * point — kebab-case strings match cass's `cli_error_kind::ErrorKind`
 * where applicable, plus a small set of FFI-local kinds:
 * `engine-closed`, `not-yet-implemented`, `internal`, `cass-error`,
 * `data-dir-missing-db`, `data-dir-missing-index`.
 *
 * Single-variant enum: keeps the natural fields (code/kind/message/hint/
 * retryable) on Swift's side as a struct-shaped associated payload while
 * satisfying UniFFI's enum-only error constraint.
 */
public enum CassError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Failed(code: Int32, kind: String, message: String, hint: String?, retryable: Bool
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CassError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCassError: FfiConverterRustBuffer {
    typealias SwiftType = CassError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CassError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Failed(
            code: try FfiConverterInt32.read(from: &buf), 
            kind: try FfiConverterString.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf), 
            hint: try FfiConverterOptionString.read(from: &buf), 
            retryable: try FfiConverterBool.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CassError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Failed(code,kind,message,hint,retryable):
            writeInt(&buf, Int32(1))
            FfiConverterInt32.write(code, into: &buf)
            FfiConverterString.write(kind, into: &buf)
            FfiConverterString.write(message, into: &buf)
            FfiConverterOptionString.write(hint, into: &buf)
            FfiConverterBool.write(retryable, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCassError_lift(_ buf: RustBuffer) throws -> CassError {
    return try FfiConverterTypeCassError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCassError_lower(_ value: CassError) -> RustBuffer {
    return FfiConverterTypeCassError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Role of a single message in a transcript.
 *
 * Maps cass-internal `crate::model::types::MessageRole` to a UniFFI enum.
 * The tuple variant `Other(String)` becomes a struct variant
 * `Other { label }` per SURFACE.md to keep Swift's `case .other(label:)`
 * labelling consistent.
 */

public enum MessageRole: Equatable, Hashable {
    
    case user
    case agent
    case tool
    case system
    case other(label: String
    )





}

#if compiler(>=6)
extension MessageRole: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageRole: FfiConverterRustBuffer {
    typealias SwiftType = MessageRole

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageRole {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .user
        
        case 2: return .agent
        
        case 3: return .tool
        
        case 4: return .system
        
        case 5: return .other(label: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MessageRole, into buf: inout [UInt8]) {
        switch value {
        
        
        case .user:
            writeInt(&buf, Int32(1))
        
        
        case .agent:
            writeInt(&buf, Int32(2))
        
        
        case .tool:
            writeInt(&buf, Int32(3))
        
        
        case .system:
            writeInt(&buf, Int32(4))
        
        
        case let .other(label):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(label, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageRole_lift(_ buf: RustBuffer) throws -> MessageRole {
    return try FfiConverterTypeMessageRole.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageRole_lower(_ value: MessageRole) -> RustBuffer {
    return FfiConverterTypeMessageRole.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Search-mode discriminator. The actor wrap dispatches on the variant
 * to the corresponding cass `SearchClient` method (lexical → `search`
 * with default mode, semantic/hybrid → `search_semantic`/`search_hybrid`
 * — wired incrementally as the next beads land).
 */

public enum SearchOpts: Equatable, Hashable {
    
    case hybrid(limit: UInt32, timeFilter: TimeFilter?
    )
    case lexical(limit: UInt32
    )
    case semantic(limit: UInt32, model: String?
    )





}

#if compiler(>=6)
extension SearchOpts: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchOpts: FfiConverterRustBuffer {
    typealias SwiftType = SearchOpts

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchOpts {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .hybrid(limit: try FfiConverterUInt32.read(from: &buf), timeFilter: try FfiConverterOptionTypeTimeFilter.read(from: &buf)
        )
        
        case 2: return .lexical(limit: try FfiConverterUInt32.read(from: &buf)
        )
        
        case 3: return .semantic(limit: try FfiConverterUInt32.read(from: &buf), model: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SearchOpts, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .hybrid(limit,timeFilter):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(limit, into: &buf)
            FfiConverterOptionTypeTimeFilter.write(timeFilter, into: &buf)
            
        
        case let .lexical(limit):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(limit, into: &buf)
            
        
        case let .semantic(limit,model):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(limit, into: &buf)
            FfiConverterOptionString.write(model, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchOpts_lift(_ buf: RustBuffer) throws -> SearchOpts {
    return try FfiConverterTypeSearchOpts.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchOpts_lower(_ value: SearchOpts) -> RustBuffer {
    return FfiConverterTypeSearchOpts.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeConversation: FfiConverterRustBuffer {
    typealias SwiftType = Conversation?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeConversation.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeConversation.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTimeFilter: FfiConverterRustBuffer {
    typealias SwiftType = TimeFilter?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTimeFilter.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTimeFilter.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessage: FfiConverterRustBuffer {
    typealias SwiftType = [Message]

    public static func write(_ value: [Message], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Message] {
        let len: Int32 = try readInt(&buf)
        var seq = [Message]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspace: FfiConverterRustBuffer {
    typealias SwiftType = [Workspace]

    public static func write(_ value: [Workspace], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspace.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Workspace] {
        let len: Int32 = try readInt(&buf)
        var seq = [Workspace]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspace.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureCassFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cass_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_close() != 62378) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_data_dir() != 7285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_expand_around() != 8805) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_list_workspaces() != 15361) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_load_conversation() != 12978) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_search() != 2872) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_method_cassengine_version() != 27281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_constructor_cassengine_open() != 62190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cass_ffi_checksum_constructor_cassengine_probe() != 18036) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCassFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all